### ISSUE TITLE
Determine number of cards drawn

### ISSUE THREAD

**Issue by stronglink** [stronglink/crucibletracker-issues#1]
Consider effects like Doc Bookton and Masterplan into Battlefleet

**Comment by jacketattack** [comment]
@stronglink let's chat about this on the phone sometime this week. Want to nail down specifically what we mean by 'draw cards' and the work involved in that. After some early investigation, I am seeing a wide spread in the data structure of the events of cards like Arise!, to Battle Fleet, to Help from Future Self.

**Comment by stronglink** [comment]
Moved to https://github.com/granttitus/crucibletracker-analyzer/issues
