### ISSUE TITLE
Sorting out of order when players switch decks

### ISSUE THREAD

**Issue by stronglink** [stronglink/crucibletracker-issues#11]

**Comment by jacketattack** [comment]
could u explain this more? sorry can't follow what the bug is

**Comment by stronglink** [comment]
In this table decks are sorted by their number of games. If I play deck A 3 times, then you play deck A 2 times, the table will consider the deck to have been played 5 times, despite only 3 of those being me.

![Screen Shot 2019-05-08 at 10 16 09 PM](https://user-images.githubusercontent.com/49877530/57422646-ea5aac00-71de-11e9-887d-66cdb78e093e.png)

**Comment by stronglink** [comment]
![Screen Shot 2019-05-18 at 1 30 10 AM](https://user-images.githubusercontent.com/49877530/57965041-8043b480-790c-11e9-86e0-9f5198cc9ca0.png)

**Comment by ira212** [comment]
Right. The intended behavior is that it should only count games played by me when sorted by Games Played.

**Comment by ira212** [comment]
And that link is specifically for this player: https://www.thecrucibletracker.com/users/firesa1

**Comment by stronglink** [comment]
Fixed!

**Comment by ira212** [comment]
Nice progress! :)
