### ISSUE TITLE
Average Turn per Deck

### ISSUE THREAD

**Issue by Zarathustra05** [stronglink/crucibletracker-issues#14]
I currently keep a spread sheet that tells me who I win and lose to and on what turn. This tracks almost all of that now and even tracks how many turns each game goes to. However, on the main display it would be useful to see average turns games take for each deck to get a quick view of overall deck speeds when comparing decks to one another.

**Comment by stronglink** [comment]
Great suggestion. This feature is now live.

![Screen Shot 2019-05-18 at 12 43 03 AM](https://user-images.githubusercontent.com/49877530/57964625-090b2200-7906-11e9-8bbd-3a2d59bd2cf0.png)
