### ISSUE TITLE
Opponent / Rival Tracker

### ISSUE THREAD

**Issue by bensissel** [stronglink/crucibletracker-issues#23]
Would like to see some sort of filter where you can track your win/loss record against specific opponents and detail > decks used for the matches

**Comment by stronglink** [comment]
Thanks for the suggestions. You can now view match data against a specific opponent.

**Comment by jacketattack** [comment]
@bensissel As @stronglink said, you can now filter by opponent on the summary screen for a deck using the 'Opponent' text box.

![image](https://user-images.githubusercontent.com/3688456/58437016-15c20f80-8096-11e9-9ac3-143906714de8.png)

closing this issue as resolved.
