### ISSUE TITLE
Chains 

### ISSUE THREAD

**Issue by Rognetudjiu** [stronglink/crucibletracker-issues#9]
Hi ! :)
It will be good to know the number of chains (if any) taken by each deck at the beginning of the game. (It is not the same to loose or win with 0 chains than with 10... :D)  And maybe the total of chains after the entire game. 
Thanks !
(Sorry if it has already been ask, i haven't seen it)

**Comment by stronglink** [comment]
Your idea is fabulous. I will see to adding this.

**Comment by jacketattack** [comment]
@Rognetudjiu it's live, check it out!

**Comment by Rognetudjiu** [comment]
Awesome ! 😊 Thanks a lot !

Provenance : Courrier<https://go.microsoft.com/fwlink/?LinkId=550986> pour Windows 10

________________________________
De : Trevor May <notifications@github.com>
Envoyé : Tuesday, May 14, 2019 10:45:28 PM
À : stronglink/crucibletracker-issues
Cc : Rognetudjiu; Mention
Objet : Re: [stronglink/crucibletracker-issues] Chains (#9)


@Rognetudjiu<https://github.com/Rognetudjiu> it's live, check it out!
